language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t raghukumarm/react-client-container -f ./client/Dockerfile.dev ./client

script:
  # - docker run raghukumarm/docker-react npm run test -- --coverage
  - docker run -e CI=true raghukumarm/react-client-container npm run test

after_success:
  - docker build -t rahgukumarm/multi-client ./client 
  - docker build -t rahgukumarm/multi-nginx ./nginx 
  - docker build -t rahgukumarm/multi-server ./server 
  - docker build -t rahgukumarm/multi-worker ./worker 
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # publish images to docker hub
  - docker push rahgukumarm/multi-client
  - docker push rahgukumarm/multi-nginx
  - docker push rahgukumarm/multi-server
  - docker push rahgukumarm/multi-worker